spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:bsp
    username: sa
    password:
    driver-class-name: org.h2.Driver

